In [5]:
!pip install spacy
!pip install textract
import os
import re
import nltk
import spacy
import string
import textract
import pandas as pd
import seaborn as sns
from matplotlib import pylab
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: spacy in c:\users\naveen\anaconda3\lib\site-packages (3.6.1)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (8.1.12)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (2.28.1)
Requirement already satisfied: numpy>=1.15.0 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (1.21.5)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (3.0.8)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (4.64.1)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (1.1.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (2.0.9)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (1.10.5)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (5.2.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (3.3.0)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (1.0.4)
Requirement already satisfied: jinja2 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (3.1.2)
Requirement already satisfied: packaging>=20.0 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (22.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (1.0.9)
Requirement already satisfied: pathy>=0.10.0 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (0.10.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (2.4.7)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (2.0.7)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (0.9.0)
Requirement already satisfied: setuptools in c:\users\naveen\anaconda3\lib\site-packages (from spacy) (65.6.3)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\naveen\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\naveen\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\naveen\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\naveen\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\naveen\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.13)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\naveen\anaconda3\lib\site-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.7.10)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\naveen\anaconda3\lib\site-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.1.1)
Requirement already satisfied: colorama in c:\users\naveen\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\naveen\anaconda3\lib\site-packages (from typer<0.10.0,>=0.3.0->spacy) (8.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\naveen\anaconda3\lib\site-packages (from jinja2->spacy) (2.0.1)

WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.1.5 requires pyqt5<5.13, which is not installed.
spyder 5.1.5 requires pyqtwebengine<5.13, which is not installed.
yfinance 0.2.3 requires beautifulsoup4>=4.11.1, but you have beautifulsoup4 4.8.2 which is incompatible.
tensorflow-intel 2.11.0 requires keras<2.12,>=2.11.0, but you have keras 2.10.0 which is incompatible.
tensorflow-intel 2.11.0 requires tensorboard<2.12,>=2.11, but you have tensorboard 2.10.1 which is incompatible.
tensorflow-intel 2.11.0 requires tensorflow-estimator<2.12,>=2.11.0, but you have tensorflow-estimator 2.10.0 which is incompatible.
conda-repo-cli 1.0.27 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.27 requires nbformat==5.4.0, but you have nbformat 5.7.0 which is incompatible.
anaconda-client 1.11.0 requires six>=1.15.0, but you have six 1.12.0 which is incompatible.
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\naveen\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\naveen\anaconda3\lib\site-packages)

Collecting textract
  Downloading textract-1.6.5-py3-none-any.whl (23 kB)
Collecting pdfminer.six==20191110
  Downloading pdfminer.six-20191110-py2.py3-none-any.whl (5.6 MB)
     ---------------------------------------- 5.6/5.6 MB 5.8 MB/s eta 0:00:00
Collecting six~=1.12.0
  Downloading six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting xlrd~=1.2.0
  Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
     -------------------------------------- 103.3/103.3 kB 5.8 MB/s eta 0:00:00
Collecting SpeechRecognition~=3.8.1
  Downloading SpeechRecognition-3.8.1-py2.py3-none-any.whl (32.8 MB)
     ---------------------------------------- 32.8/32.8 MB 5.7 MB/s eta 0:00:00
Collecting python-pptx~=0.6.18
  Downloading python_pptx-0.6.22-py3-none-any.whl (471 kB)
     -------------------------------------- 471.5/471.5 kB 5.9 MB/s eta 0:00:00
Collecting beautifulsoup4~=4.8.0
  Downloading beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
     -------------------------------------- 106.9/106.9 kB 6.0 MB/s eta 0:00:00
Collecting chardet==3.*
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     -------------------------------------- 133.4/133.4 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: docx2txt~=0.8 in c:\users\naveen\anaconda3\lib\site-packages (from textract) (0.8)
Collecting argcomplete~=1.10.0
  Downloading argcomplete-1.10.3-py2.py3-none-any.whl (36 kB)
Collecting extract-msg<=0.29.*
  Downloading extract_msg-0.28.7-py2.py3-none-any.whl (69 kB)
     ---------------------------------------- 69.0/69.0 kB ? eta 0:00:00
Requirement already satisfied: sortedcontainers in c:\users\naveen\anaconda3\lib\site-packages (from pdfminer.six==20191110->textract) (2.4.0)
Collecting pycryptodome
  Downloading pycryptodome-3.18.0-cp35-abi3-win_amd64.whl (1.7 MB)
     ---------------------------------------- 1.7/1.7 MB 6.9 MB/s eta 0:00:00
Requirement already satisfied: soupsieve>=1.2 in c:\users\naveen\anaconda3\lib\site-packages (from beautifulsoup4~=4.8.0->textract) (2.3.2.post1)
Requirement already satisfied: olefile>=0.46 in c:\users\naveen\anaconda3\lib\site-packages (from extract-msg<=0.29.*->textract) (0.46)
Collecting ebcdic>=1.1.1
  Downloading ebcdic-1.1.1-py2.py3-none-any.whl (128 kB)
     -------------------------------------- 128.5/128.5 kB 7.4 MB/s eta 0:00:00
Collecting imapclient==2.1.0
  Downloading IMAPClient-2.1.0-py2.py3-none-any.whl (73 kB)
     ---------------------------------------- 74.0/74.0 kB 4.0 MB/s eta 0:00:00
Collecting compressed-rtf>=1.0.6
  Downloading compressed_rtf-1.0.6.tar.gz (5.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: tzlocal>=2.1 in c:\users\naveen\anaconda3\lib\site-packages (from extract-msg<=0.29.*->textract) (4.2)
Requirement already satisfied: lxml>=3.1.0 in c:\users\naveen\anaconda3\lib\site-packages (from python-pptx~=0.6.18->textract) (4.9.2)
Requirement already satisfied: Pillow<=9.5.0,>=3.3.2 in c:\users\naveen\anaconda3\lib\site-packages (from python-pptx~=0.6.18->textract) (9.3.0)
Requirement already satisfied: XlsxWriter>=0.5.7 in c:\users\naveen\anaconda3\lib\site-packages (from python-pptx~=0.6.18->textract) (3.0.3)
Requirement already satisfied: pytz-deprecation-shim in c:\users\naveen\anaconda3\lib\site-packages (from tzlocal>=2.1->extract-msg<=0.29.*->textract) (0.1.0.post0)
Requirement already satisfied: tzdata in c:\users\naveen\anaconda3\lib\site-packages (from tzlocal>=2.1->extract-msg<=0.29.*->textract) (2022.6)
Building wheels for collected packages: compressed-rtf
  Building wheel for compressed-rtf (setup.py): started
  Building wheel for compressed-rtf (setup.py): finished with status 'done'
  Created wheel for compressed-rtf: filename=compressed_rtf-1.0.6-py3-none-any.whl size=6186 sha256=2d8aad78d0452fb9d41bfb0a98484315afc47ee483e6008336879e294ce3f9ad
  Stored in directory: c:\users\naveen\appdata\local\pip\cache\wheels\a8\9a\17\979e238fca71d5843b6f6b6b1e3e901ce9da00ffe73d1aa66f
Successfully built compressed-rtf
Installing collected packages: SpeechRecognition, ebcdic, compressed-rtf, chardet, argcomplete, xlrd, six, python-pptx, pycryptodome, beautifulsoup4, pdfminer.six, imapclient, extract-msg, textract
  Attempting uninstall: chardet
    Found existing installation: chardet 4.0.0
    Uninstalling chardet-4.0.0:
      Successfully uninstalled chardet-4.0.0
  Attempting uninstall: xlrd
    Found existing installation: xlrd 2.0.1
    Uninstalling xlrd-2.0.1:
      Successfully uninstalled xlrd-2.0.1
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.11.1
    Uninstalling beautifulsoup4-4.11.1:
      Successfully uninstalled beautifulsoup4-4.11.1
Successfully installed SpeechRecognition-3.8.1 argcomplete-1.10.3 beautifulsoup4-4.8.2 chardet-3.0.4 compressed-rtf-1.0.6 ebcdic-1.1.1 extract-msg-0.28.7 imapclient-2.1.0 pdfminer.six-20191110 pycryptodome-3.18.0 python-pptx-0.6.22 six-1.12.0 textract-1.6.5 xlrd-1.2.0

In [16]:
os.listdir('C:\\Users\\NAVEEN\\Downloads\\Resume Docx\\Resumes')

['Peoplesoft resumes',
 'Reactjs Developer',
 'SQL Developer Lightning insight',
 'workday resumes']

In [17]:
file_path1 = []
category1  = []
directory1 = 'C:\\Users\\NAVEEN\\Downloads\\Resume Docx\\Resumes\\PeopleSoft resumes/'
for i in os.listdir(directory1):
    if i.endswith('.docx'):
        os.path.join(directory1, i)
        file_path1.append((textract.process(os.path.join(directory1, i))).decode('utf-8'))
        category1.append('PeopleSoft resumes')

In [18]:
df1 = pd.DataFrame(data = file_path1 , columns = ['Raw_Details'])
df1['Category1'] = category1
df1

                                         Raw_Details           Category1
0  Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...  PeopleSoft resumes
1  Classification: Internal\n\nClassification: In...  PeopleSoft resumes
2  SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n...  PeopleSoft resumes
3  PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...  PeopleSoft resumes
4  PeopleSoft Administration\n\n \n\nVivekanand S...  PeopleSoft resumes
5  Hari Narayana \t\t              \n\n\t\n\n\n\n...  PeopleSoft resumes
6  Murali\t\t       \n\n\t\n\n\n\n\n\n\n\n\n\n\n\...  PeopleSoft resumes
7  Priyabrata Hota\n\n\n\n\n\nCAREER OBJECTIVE\t\...  PeopleSoft resumes
8  Tanna Sujatha \n\n\n\n\n\n\n\nOBJECTIVE\n\nSee...  PeopleSoft resumes
9  C O N T A C T :\n\n\n\nAddress: Manyata Tech P...  PeopleSoft resumes

In [19]:
file_path2 = []
category2  = []
directory2 = 'C:\\Users\\NAVEEN\\Downloads\\Resume Docx\\Resumes\\Reactjs Developer/'
for i in os.listdir(directory2):
    if i.endswith('.docx'):
        os.path.join(directory2, i)
        file_path2.append((textract.process(os.path.join(directory2, i))).decode('utf-8'))
        category2.append('Reactjs Developer')

In [20]:
df2 = pd.DataFrame(data = file_path2 , columns = ['Raw_Details'])
df2['Category2'] = category2
df2

                                          Raw_Details          Category2
0   Name: Ravali P \n\n\n\n                       ...  Reactjs Developer
1   SUSOVAN  BAG   \n\nSeeking  a  challenging  po...  Reactjs Developer
2   Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...  Reactjs Developer
3   HARIPRIYA BATTINA \n\nExperience as UI Develop...  Reactjs Developer
4   KAMALAKAR REDDY. A \n\nLinked In: https://www....  Reactjs Developer
5   Naveen Sadhu\n\n\n\n\n\nTitle: software develo...  Reactjs Developer
6   PRAGNYA PATTNAIK\n\n \n\n \n\n \n\n Expertise:...  Reactjs Developer
7   SARALA MADASU\n\nSARALA MADASU\n\n 204,Sri ge...  Reactjs Developer
8   Thirupathamma Balla\n\n\n\nSUMMARY:\n\n\n\n2.8...  Reactjs Developer
9   Ui-Developer/ React JS Developer \n\nNAME: KRI...  Reactjs Developer
10  Ui-Developer/ React JS Developer \n\nNAME: KRI...  Reactjs Developer
11  Kotani Durga Prasad\n\n\n\n\n\nObjective:\n\n\...  Reactjs Developer
12  Venkatalakshmi Pedireddy\n\nSoftware Developer...  Reactjs Developer
13  KAMBALA SAI SURENDRA   \n\n \n\n \n\n \n\n\n\n...  Reactjs Developer
14  MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...  Reactjs Developer
15  MAREEDU LOKESH BABU\n\n\n\nPROFESSIONAL OVERVI...  Reactjs Developer
16  MD KHIZARUDDIN RAUF \n\n \t EXPERIENCE \n\n   ...  Reactjs Developer
17  Pranish Sonone\n\n\t\t\n\n\n\n\n\n\n\n\n\nCare...  Reactjs Developer
18  Ranga Gaganam  \n\n\n\n \n\nProfessional\n\n \...  Reactjs Developer
19  SHAIK ABDUL SHARUK   \n\n2 years’ Experience i...  Reactjs Developer

In [22]:
file_path3 = []
category3 = []
directory3 = 'C:\\Users\\NAVEEN\\Downloads\\Resume Docx\\Resumes\\SQL Developer Lightning insight/'
for i in os.listdir(directory3):
    if i.endswith('.docx'):
        os.path.join(directory3, i)
        file_path3.append((textract.process(os.path.join(directory3, i))).decode('utf-8'))
        category3.append('SQL Developer Lightning insight')

In [23]:
df3 = pd.DataFrame(data = file_path3 , columns = ['Raw_Details'])
df3['Category3'] = category3
df3

,Raw_Details,Category3
0,ANIL KUMAR MADDUKURI \t\t\n\nSQL & MSBI Devel...,SQL Developer Lightning insight
1,Aradhana Tripathi\n\n\n\nCurrent Location: Gac...,SQL Developer Lightning insight
2,BUDDHA VAMSI ...,SQL Developer Lightning insight
3,KAMBALLA PRADEEP ...,SQL Developer Lightning insight
4,Resume\n\nName : Neeraj Mishra\n\n\n\nExp...,SQL Developer Lightning insight
5,SQL DEVELOPER\n\nName: - Bandi prem sai\n\n\...,SQL Developer Lightning insight
6,SQL SERVER DEVELOPER\n\n\n\n\n\nP. Syam Kumar ...,SQL Developer Lightning insight
7,RAJU PAVANA KUMARI\n\n\n\n\t\n\n\tProfessional...,SQL Developer Lightning insight
8,resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...,SQL Developer Lightning insight
9,Name: Ramesh\n\n\t\n\n\tCareer Objective: \n\n...,SQL Developer Lightning insight
10,SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...,SQL Developer Lightning insight

In [24]:
file_path4 = []
category4 = []
directory4 = 'C:\\Users\\NAVEEN\\Downloads\\Resume Docx\\Resumes\\workday resumes/'
for i in os.listdir(directory4):
    if i.endswith('.docx'):
        os.path.join(directory4, i)
        file_path4.append((textract.process(os.path.join(directory4, i))).decode('utf-8'))
        category4.append('workday resumes')

In [25]:
df4 = pd.DataFrame(data = file_path4 , columns = ['Raw_Details'])
df4['Category4'] = category4
df4

                                          Raw_Details        Category4
0   Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...  workday resumes
1   Name         : Gopi Krishna Reddy\n\n\t\t     ...  workday resumes
2   G Himaja\n\n                                  ...  workday resumes
3   JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...  workday resumes
4   Mooraboyina Guravaiah\n\nWorkday Integration S...  workday resumes
5   VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...  workday resumes
6   Workday HCM  Techno functional Consultant     ...  workday resumes
7   Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...  workday resumes
8   Srikanth (WORKDAY hCM Consultant)\t           ...  workday resumes
9   WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...  workday resumes
10  Vinay kumar .v\nWorkday Functional Consultant\...  workday resumes

In [29]:
resume_data = df1.append([df2, df3, df4], ignore_index = True)
resume_data

,Raw_Details,Category1,Category2,Category3,Category4
0,Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...,PeopleSoft resumes,NaN,NaN,NaN
1,Classification: Internal\n\nClassification: In...,PeopleSoft resumes,NaN,NaN,NaN
2,"SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n...",PeopleSoft resumes,NaN,NaN,NaN
3,PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...,PeopleSoft resumes,NaN,NaN,NaN
4,PeopleSoft Administration\n\n \n\nVivekanand S...,PeopleSoft resumes,NaN,NaN,NaN
5,Hari Narayana \t\t \n\n\t\n\n\n\n...,PeopleSoft resumes,NaN,NaN,NaN
6,Murali\t\t \n\n\t\n\n\n\n\n\n\n\n\n\n\n\...,PeopleSoft resumes,NaN,NaN,NaN
7,Priyabrata Hota\n\n\n\n\n\nCAREER OBJECTIVE\t\...,PeopleSoft resumes,NaN,NaN,NaN
8,Tanna Sujatha \n\n\n\n\n\n\n\nOBJECTIVE\n\nSee...,PeopleSoft resumes,NaN,NaN,NaN
9,C O N T A C T :\n\n\n\nAddress: Manyata Tech P...,PeopleSoft resumes,NaN,NaN,NaN
10,Name: Ravali P \n\n\n\n ...,NaN,Reactjs Developer,NaN,NaN
11,SUSOVAN BAG \n\nSeeking a challenging po...,NaN,Reactjs Developer,NaN,NaN
12,Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...,NaN,Reactjs Developer,NaN,NaN
13,HARIPRIYA BATTINA \n\nExperience as UI Develop...,NaN,Reactjs Developer,NaN,NaN
14,KAMALAKAR REDDY. A \n\nLinked In: https://www....,NaN,Reactjs Developer,NaN,NaN
15,Naveen Sadhu\n\n\n\n\n\nTitle: software develo...,NaN,Reactjs Developer,NaN,NaN
16,PRAGNYA PATTNAIK\n\n \n\n \n\n \n\n Expertise:...,NaN,Reactjs Developer,NaN,NaN
17,"SARALA MADASU\n\nSARALA MADASU\n\n 204,Sri ge...",NaN,Reactjs Developer,NaN,NaN
18,Thirupathamma Balla\n\n\n\nSUMMARY:\n\n\n\n2.8...,NaN,Reactjs Developer,NaN,NaN
19,Ui-Developer/ React JS Developer \n\nNAME: KRI...,NaN,Reactjs Developer,NaN,NaN
20,Ui-Developer/ React JS Developer \n\nNAME: KRI...,NaN,Reactjs Developer,NaN,NaN
21,Kotani Durga Prasad\n\n\n\n\n\nObjective:\n\n\...,NaN,Reactjs Developer,NaN,NaN
22,Venkatalakshmi Pedireddy\n\nSoftware Developer...,NaN,Reactjs Developer,NaN,NaN
23,KAMBALA SAI SURENDRA \n\n \n\n \n\n \n\n\n\n...,NaN,Reactjs Developer,NaN,NaN
24,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,NaN,Reactjs Developer,NaN,NaN
25,MAREEDU LOKESH BABU\n\n\n\nPROFESSIONAL OVERVI...,NaN,Reactjs Developer,NaN,NaN
26,MD KHIZARUDDIN RAUF \n\n \t EXPERIENCE \n\n ...,NaN,Reactjs Developer,NaN,NaN
27,Pranish Sonone\n\n\t\t\n\n\n\n\n\n\n\n\n\nCare...,NaN,Reactjs Developer,NaN,NaN
28,Ranga Gaganam \n\n\n\n \n\nProfessional\n\n \...,NaN,Reactjs Developer,NaN,NaN
29,SHAIK ABDUL SHARUK \n\n2 years’ Experience i...,NaN,Reactjs Developer,NaN,NaN
30,ANIL KUMAR MADDUKURI \t\t\n\nSQL & MSBI Devel...,NaN,NaN,SQL Developer Lightning insight,NaN
31,Aradhana Tripathi\n\n\n\nCurrent Location: Gac...,NaN,NaN,SQL Developer Lightning insight,NaN
32,BUDDHA VAMSI ...,NaN,NaN,SQL Developer Lightning insight,NaN
33,KAMBALLA PRADEEP ...,NaN,NaN,SQL Developer Lightning insight,NaN
34,Resume\n\nName : Neeraj Mishra\n\n\n\nExp...,NaN,NaN,SQL Developer Lightning insight,NaN
35,SQL DEVELOPER\n\nName: - Bandi prem sai\n\n\...,NaN,NaN,SQL Developer Lightning insight,NaN
36,SQL SERVER DEVELOPER\n\n\n\n\n\nP. Syam Kumar ...,NaN,NaN,SQL Developer Lightning insight,NaN
37,RAJU PAVANA KUMARI\n\n\n\n\t\n\n\tProfessional...,NaN,NaN,SQL Developer Lightning insight,NaN
38,resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...,NaN,NaN,SQL Developer Lightning insight,NaN
39,Name: Ramesh\n\n\t\n\n\tCareer Objective: \n\n...,NaN,NaN,SQL Developer Lightning insight,NaN
40,SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...,NaN,NaN,SQL Developer Lightning insight,NaN
41,Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...,NaN,NaN,NaN,workday resumes
42,Name : Gopi Krishna Reddy\n\n\t\t ...,NaN,NaN,NaN,workday resumes
43,G Himaja\n\n ...,NaN,NaN,NaN,workday resumes
44,JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...,NaN,NaN,NaN,workday resumes
45,Mooraboyina Guravaiah\n\nWorkday Integration S...,NaN,NaN,NaN,workday resumes
46,VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...,NaN,NaN,NaN,workday resumes
47,Workday HCM Techno functional Consultant ...,NaN,NaN,NaN,workday resumes
48,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,NaN,NaN,NaN,workday resumes
49,Srikanth (WORKDAY hCM Consultant)\t ...,NaN,NaN,NaN,workday resumes
50,WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...,NaN,NaN,NaN,workday resumes
51,Vinay kumar .v\nWorkday Functional Consultant\...,NaN,NaN,NaN,workday resumes

In [32]:
resume_data['Category'] = category1 + category2 + category3 + category4
resume_data

,Raw_Details,Category
0,Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...,PeopleSoft resumes
1,Classification: Internal\n\nClassification: In...,PeopleSoft resumes
2,"SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n...",PeopleSoft resumes
3,PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...,PeopleSoft resumes
4,PeopleSoft Administration\n\n \n\nVivekanand S...,PeopleSoft resumes
5,Hari Narayana \t\t \n\n\t\n\n\n\n...,PeopleSoft resumes
6,Murali\t\t \n\n\t\n\n\n\n\n\n\n\n\n\n\n\...,PeopleSoft resumes
7,Priyabrata Hota\n\n\n\n\n\nCAREER OBJECTIVE\t\...,PeopleSoft resumes
8,Tanna Sujatha \n\n\n\n\n\n\n\nOBJECTIVE\n\nSee...,PeopleSoft resumes
9,C O N T A C T :\n\n\n\nAddress: Manyata Tech P...,PeopleSoft resumes
10,Name: Ravali P \n\n\n\n ...,Reactjs Developer
11,SUSOVAN BAG \n\nSeeking a challenging po...,Reactjs Developer
12,Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...,Reactjs Developer
13,HARIPRIYA BATTINA \n\nExperience as UI Develop...,Reactjs Developer
14,KAMALAKAR REDDY. A \n\nLinked In: https://www....,Reactjs Developer
15,Naveen Sadhu\n\n\n\n\n\nTitle: software develo...,Reactjs Developer
16,PRAGNYA PATTNAIK\n\n \n\n \n\n \n\n Expertise:...,Reactjs Developer
17,"SARALA MADASU\n\nSARALA MADASU\n\n 204,Sri ge...",Reactjs Developer
18,Thirupathamma Balla\n\n\n\nSUMMARY:\n\n\n\n2.8...,Reactjs Developer
19,Ui-Developer/ React JS Developer \n\nNAME: KRI...,Reactjs Developer
20,Ui-Developer/ React JS Developer \n\nNAME: KRI...,Reactjs Developer
21,Kotani Durga Prasad\n\n\n\n\n\nObjective:\n\n\...,Reactjs Developer
22,Venkatalakshmi Pedireddy\n\nSoftware Developer...,Reactjs Developer
23,KAMBALA SAI SURENDRA \n\n \n\n \n\n \n\n\n\n...,Reactjs Developer
24,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,Reactjs Developer
25,MAREEDU LOKESH BABU\n\n\n\nPROFESSIONAL OVERVI...,Reactjs Developer
26,MD KHIZARUDDIN RAUF \n\n \t EXPERIENCE \n\n ...,Reactjs Developer
27,Pranish Sonone\n\n\t\t\n\n\n\n\n\n\n\n\n\nCare...,Reactjs Developer
28,Ranga Gaganam \n\n\n\n \n\nProfessional\n\n \...,Reactjs Developer
29,SHAIK ABDUL SHARUK \n\n2 years’ Experience i...,Reactjs Developer
30,ANIL KUMAR MADDUKURI \t\t\n\nSQL & MSBI Devel...,SQL Developer Lightning insight
31,Aradhana Tripathi\n\n\n\nCurrent Location: Gac...,SQL Developer Lightning insight
32,BUDDHA VAMSI ...,SQL Developer Lightning insight
33,KAMBALLA PRADEEP ...,SQL Developer Lightning insight
34,Resume\n\nName : Neeraj Mishra\n\n\n\nExp...,SQL Developer Lightning insight
35,SQL DEVELOPER\n\nName: - Bandi prem sai\n\n\...,SQL Developer Lightning insight
36,SQL SERVER DEVELOPER\n\n\n\n\n\nP. Syam Kumar ...,SQL Developer Lightning insight
37,RAJU PAVANA KUMARI\n\n\n\n\t\n\n\tProfessional...,SQL Developer Lightning insight
38,resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...,SQL Developer Lightning insight
39,Name: Ramesh\n\n\t\n\n\tCareer Objective: \n\n...,SQL Developer Lightning insight
40,SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...,SQL Developer Lightning insight
41,Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...,workday resumes
42,Name : Gopi Krishna Reddy\n\n\t\t ...,workday resumes
43,G Himaja\n\n ...,workday resumes
44,JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...,workday resumes
45,Mooraboyina Guravaiah\n\nWorkday Integration S...,workday resumes
46,VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...,workday resumes
47,Workday HCM Techno functional Consultant ...,workday resumes
48,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,workday resumes
49,Srikanth (WORKDAY hCM Consultant)\t ...,workday resumes
50,WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...,workday resumes
51,Vinay kumar .v\nWorkday Functional Consultant\...,workday resumes

In [33]:
resume_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Raw_Details  52 non-null     object
 1   Category     52 non-null     object
dtypes: object(2)
memory usage: 960.0+ bytes

In [34]:
resume_data.to_csv('Raw_Resume.csv', index=False)

In [35]:
resume_data = pd.read_csv("Raw_Resume.csv")
resume_data

,Raw_Details,Category
0,Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...,PeopleSoft resumes
1,Classification: Internal\n\nClassification: In...,PeopleSoft resumes
2,"SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n...",PeopleSoft resumes
3,PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...,PeopleSoft resumes
4,PeopleSoft Administration\n\n \n\nVivekanand S...,PeopleSoft resumes
5,Hari Narayana \t\t \n\n\t\n\n\n\n...,PeopleSoft resumes
6,Murali\t\t \n\n\t\n\n\n\n\n\n\n\n\n\n\n\...,PeopleSoft resumes
7,Priyabrata Hota\n\n\n\n\n\nCAREER OBJECTIVE\t\...,PeopleSoft resumes
8,Tanna Sujatha \n\n\n\n\n\n\n\nOBJECTIVE\n\nSee...,PeopleSoft resumes
9,C O N T A C T :\n\n\n\nAddress: Manyata Tech P...,PeopleSoft resumes
10,Name: Ravali P \n\n\n\n ...,Reactjs Developer
11,SUSOVAN BAG \n\nSeeking a challenging po...,Reactjs Developer
12,Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...,Reactjs Developer
13,HARIPRIYA BATTINA \n\nExperience as UI Develop...,Reactjs Developer
14,KAMALAKAR REDDY. A \n\nLinked In: https://www....,Reactjs Developer
15,Naveen Sadhu\n\n\n\n\n\nTitle: software develo...,Reactjs Developer
16,PRAGNYA PATTNAIK\n\n \n\n \n\n \n\n Expertise:...,Reactjs Developer
17,"SARALA MADASU\n\nSARALA MADASU\n\n 204,Sri ge...",Reactjs Developer
18,Thirupathamma Balla\n\n\n\nSUMMARY:\n\n\n\n2.8...,Reactjs Developer
19,Ui-Developer/ React JS Developer \n\nNAME: KRI...,Reactjs Developer
20,Ui-Developer/ React JS Developer \n\nNAME: KRI...,Reactjs Developer
21,Kotani Durga Prasad\n\n\n\n\n\nObjective:\n\n\...,Reactjs Developer
22,Venkatalakshmi Pedireddy\n\nSoftware Developer...,Reactjs Developer
23,KAMBALA SAI SURENDRA \n\n \n\n \n\n \n\n\n\n...,Reactjs Developer
24,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,Reactjs Developer
25,MAREEDU LOKESH BABU\n\n\n\nPROFESSIONAL OVERVI...,Reactjs Developer
26,MD KHIZARUDDIN RAUF \n\n \t EXPERIENCE \n\n ...,Reactjs Developer
27,Pranish Sonone\n\n\t\t\n\n\n\n\n\n\n\n\n\nCare...,Reactjs Developer
28,Ranga Gaganam \n\n\n\n \n\nProfessional\n\n \...,Reactjs Developer
29,SHAIK ABDUL SHARUK \n\n2 years’ Experience i...,Reactjs Developer
30,ANIL KUMAR MADDUKURI \t\t\n\nSQL & MSBI Devel...,SQL Developer Lightning insight
31,Aradhana Tripathi\n\n\n\nCurrent Location: Gac...,SQL Developer Lightning insight
32,BUDDHA VAMSI ...,SQL Developer Lightning insight
33,KAMBALLA PRADEEP ...,SQL Developer Lightning insight
34,Resume\n\nName : Neeraj Mishra\n\n\n\nExp...,SQL Developer Lightning insight
35,SQL DEVELOPER\n\nName: - Bandi prem sai\n\n\...,SQL Developer Lightning insight
36,SQL SERVER DEVELOPER\n\n\n\n\n\nP. Syam Kumar ...,SQL Developer Lightning insight
37,RAJU PAVANA KUMARI\n\n\n\n\t\n\n\tProfessional...,SQL Developer Lightning insight
38,resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...,SQL Developer Lightning insight
39,Name: Ramesh\n\n\t\n\n\tCareer Objective: \n\n...,SQL Developer Lightning insight
40,SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...,SQL Developer Lightning insight
41,Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...,workday resumes
42,Name : Gopi Krishna Reddy\n\n\t\t ...,workday resumes
43,G Himaja\n\n ...,workday resumes
44,JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...,workday resumes
45,Mooraboyina Guravaiah\n\nWorkday Integration S...,workday resumes
46,VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...,workday resumes
47,Workday HCM Techno functional Consultant ...,workday resumes
48,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,workday resumes
49,Srikanth (WORKDAY hCM Consultant)\t ...,workday resumes
50,WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...,workday resumes
51,Vinay kumar .v\nWorkday Functional Consultant\...,workday resumes